version: "3.7"
networks:
  back:

services:
  fast_api:
    build:
      dockerfile: ./docker/dockerfile
      context: .
    command: uvicorn source.main:source --host 0.0.0.0 --port 8000
    volumes:
      - ./source:/source
    env_file:
      - .env
    environment:
      - DEBUG=True
    ports:
      - 8000:8000
    networks:
      - back
