version: "3.7"

x-build: &default-build
  context: .
  dockerfile: Dockerfile

services:
  bocuse-app:
    build: *default-build
    command: uvicorn Bocuse.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
    ports:
      - 8000:8000
    networks:
      - back

  lint:
    container_name: bocuse-lint
    build: *default-build
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - back
    command: ["./scripts/start-lint.sh"]

networks:
  back:
    name: back-bocuse

